f1=open("sam.txt",'w')
f1.write("hello world")
f1.close()
f1=open("sam.txt",'r')
print(f1.read())
f1.close()
f1=open("sam.txt",'a')
f1.write("Welcome")
f1=open("sam.txt",'r')
print(f1.read())
f1.close()
